# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cartographer < Formula
  desc "CLI tool for visualizing Kubernetes resource dependencies as DOT graphs"
  homepage "https://github.com/HMetcalfeW/cartographer"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.4.0/cartographer_0.4.0_darwin_amd64.tar.gz"
      sha256 "579cf886b9b57790a6b721a7d72c64fc93a7e973521eaa204d5d7709f73e439d"

      define_method(:install) do
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.4.0/cartographer_0.4.0_darwin_arm64.tar.gz"
      sha256 "f8965c4f755185bb8b0269ac6f9535bbd78fa5c3126f1ded0d85495e06198905"

      define_method(:install) do
        bin.install "cartographer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.4.0/cartographer_0.4.0_linux_amd64.tar.gz"
      sha256 "1f23583fc7ca0a7f70601cb701ff577d735f7fb6fd0ef7b69bb52e6b8555ff7f"
      define_method(:install) do
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.4.0/cartographer_0.4.0_linux_arm64.tar.gz"
      sha256 "836fc77e00c01cf3dd933a5fc40f4190d70a848709cda20f013f79621afc3dea"
      define_method(:install) do
        bin.install "cartographer"
      end
    end
  end

  test do
    system "#{bin}/cartographer", "version"
  end
end
