# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cartographer < Formula
  desc "CLI tool for visualizing Kubernetes resource dependencies as DOT graphs"
  homepage "https://github.com/HMetcalfeW/cartographer"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.3.0/cartographer_0.3.0_darwin_amd64.tar.gz"
      sha256 "475050b2dff44a0cc563fcf449fbd5f3b840e2e13203b39dc5aa7461e5aa8dac"

      define_method(:install) do
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.3.0/cartographer_0.3.0_darwin_arm64.tar.gz"
      sha256 "21e73cd069a5b75d12daf5cb77a3c38081e7f3699fa32173f50e69ac77cf9edf"

      define_method(:install) do
        bin.install "cartographer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.3.0/cartographer_0.3.0_linux_amd64.tar.gz"
      sha256 "4d696d2301826a316c9d355de7f5494bbd131f3cdea6fc247c992efbcb687950"
      define_method(:install) do
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.3.0/cartographer_0.3.0_linux_arm64.tar.gz"
      sha256 "698d178c764bacd3e94069d3ea6d4cdf575186cbda93a6f99e7b6eacabe78a28"
      define_method(:install) do
        bin.install "cartographer"
      end
    end
  end

  test do
    system "#{bin}/cartographer", "version"
  end
end
