# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cartographer < Formula
  desc "CLI tool for visualizing Kubernetes resource dependencies as DOT graphs"
  homepage "https://github.com/HMetcalfeW/cartographer"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.2.0/cartographer_0.2.0_darwin_amd64.tar.gz"
      sha256 "fd7669030dfc4d6f72121548f2d0e8a1b3ced82aada086963008bc62c4cfa591"

      def install
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.2.0/cartographer_0.2.0_darwin_arm64.tar.gz"
      sha256 "d3f0c5eb1f8d0389cda1062d5d5de826b83b6a92a4249309c0e80caf08a1d174"

      def install
        bin.install "cartographer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.2.0/cartographer_0.2.0_linux_amd64.tar.gz"
      sha256 "adc04f00c912b25ba6016103da7724aa1a7ff9a609ee1e356376c26bb47592be"
      def install
        bin.install "cartographer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v0.2.0/cartographer_0.2.0_linux_arm64.tar.gz"
      sha256 "1d2aae512183652a83eaf20d3db3a099b420aad3cfb77dbac1e561e151f2177b"
      def install
        bin.install "cartographer"
      end
    end
  end

  test do
    system "#{bin}/cartographer", "version"
  end
end
