# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nilguard < Formula
  desc "Go static analyzer that enforces nil-check policy for pointer uses"
  homepage "https://github.com/HMetcalfe/nilguard"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HMetcalfeW/nilguard/releases/download/v0.1.0/nilguard_0.1.0_darwin_amd64.tar.gz"
      sha256 "8223579b6145dee6228e2cf2502ed36b703fd52c377481a96712e5297bd9a885"

      define_method(:install) do
        bin.install "nilguard"
        bin.install "nilguard-vet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HMetcalfeW/nilguard/releases/download/v0.1.0/nilguard_0.1.0_darwin_arm64.tar.gz"
      sha256 "ecb3dfcc8a49b55aa2b1eb328e9463ed968dc1a8e2db97ec9c8e7da9f3d28748"

      define_method(:install) do
        bin.install "nilguard"
        bin.install "nilguard-vet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/nilguard/releases/download/v0.1.0/nilguard_0.1.0_linux_amd64.tar.gz"
      sha256 "c2baa6a42762c42b933dde38dde15054a27d6fad6821782674f8767341333209"
      define_method(:install) do
        bin.install "nilguard"
        bin.install "nilguard-vet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HMetcalfeW/nilguard/releases/download/v0.1.0/nilguard_0.1.0_linux_arm64.tar.gz"
      sha256 "fa63a2177994f27c6575fe34b26730cf3ead21f7b3952e2ebbe752582080bc85"
      define_method(:install) do
        bin.install "nilguard"
        bin.install "nilguard-vet"
      end
    end
  end
end
