# This file was generated by GoReleaser. DO NOT EDIT.
cask "cartographer" do
  name "cartographer"
  desc "CLI tool for visualizing Kubernetes resource dependencies"
  homepage "https://github.com/HMetcalfeW/cartographer"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cartographer"

  on_macos do
    on_intel do
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v#{version}/cartographer_#{version}_darwin_amd64.tar.gz"
      sha256 "1d112173c002f586090954a76cd8d26b4469804808d7c7e26c272156e2b2bb06"
    end
    on_arm do
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v#{version}/cartographer_#{version}_darwin_arm64.tar.gz"
      sha256 "b856278b45fb33f6bc1d70641aa79b43fc036b82f598c090bad3a7a7f9870559"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v#{version}/cartographer_#{version}_linux_amd64.tar.gz"
      sha256 "ed8a33fd7c60fa6bfcf91150d95294353190db58d7c3ea7dbe4cfa92edcba466"
    end
    on_arm do
      url "https://github.com/HMetcalfeW/cartographer/releases/download/v#{version}/cartographer_#{version}_linux_arm64.tar.gz"
      sha256 "63ca93f3b4dfb2a2cdc50187ff77a54aba98385f7f1862aa458ec9544ac1cf63"
    end
  end

  # No zap stanza required
end
